/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // menu materi
  docs:[
    'intro',
    {
      type: 'category',
      label: 'Programming Web',
      collapsed: true,
      items: [
        'web/index',
        'web/persiapan',
        {
          HTML: [
            'web/html/index_html',
            'web/html/heading',
            'web/html/paragraf',
            'web/html/format',
            'web/html/tabel',
            'web/html/order_list'
          ],
        },
        {
          CSS: [
            'web/css/index_css'
          ],
        },
        {
          Javascript: [
            'web/javascript/index_javascript'
          ]
        },
        {
          PHP : [
            'web/php/index_php',
            {
              Laragon: [
                'web/php/laragon/index_laragon',
                'web/php/laragon/jalan_laragon',
                'web/php/laragon/versi_laragon'
              ],
            },
          ],
        }
      ]
    },
  ],
  // menu contoh
  contoh: [
    'contoh'
  ]
};
